### ISSUE TITLE
PM Review: User Authentication

### ISSUE THREAD

**Issue by lambyy** [lambyy/eventation#9]

**Comment by lambyy** [comment]
Completed user authentication.

**Comment by LochandQuay** [comment]
@lambyy 

General: 
- Would like Demo login to appear on both forms, but ultimately that's your design decision

Console Errors:
- `Warning: Hash history cannot PUSH the same path; a new entry will not be added to the history stack`
  - I think you might be pushing your root URL multiple times somewhere, causing this warning to pop up.

Styling:
- Remove bullet points from errors and make them stand out more, if possible

**Comment by lambyy** [comment]
@LochandQuay 

I put the Demo login on both forms and changed the styling of the displayed errors. I also fixed the Hash history error for the logout button so that when you logout, it only redirects to "/" if not already on "/". I think the warning only shows up now if you press the link that redirects you to the page you are already on i.e. pressing sign in when already on the sign in page will trigger that warning. Is that okay for now?

**Comment by LochandQuay** [comment]
@lambyy 

yeah I don't think there's really a way to get around that without like trying to catch the redirect before it happens.

Looks good!
